
# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(441, 376)
        calculator.setMinimumSize(QtCore.QSize(441, 0))
        calculator.setStyleSheet("QWidget{rgb(255, 246, 239)}")
        self.label = QtWidgets.QLabel(parent=calculator)
        self.label.setGeometry(QtCore.QRect(41, 71, 76, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=calculator)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 76, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_2.setObjectName("label_2")
        self.input1 = QtWidgets.QLineEdit(parent=calculator)
        self.input1.setGeometry(QtCore.QRect(210, 70, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input1.setFont(font)
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QLineEdit(parent=calculator)
        self.input2.setGeometry(QtCore.QRect(210, 120, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.input2.setFont(font)
        self.input2.setObjectName("input2")
        self.pluse = QtWidgets.QPushButton(parent=calculator)
        self.pluse.setGeometry(QtCore.QRect(204, 192, 75, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pluse.setFont(font)
        self.pluse.setObjectName("pluse")
        self.pushButton_2 = QtWidgets.QPushButton(parent=calculator)
        self.pushButton_2.setGeometry(QtCore.QRect(285, 192, 75, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=calculator)
        self.pushButton_3.setGeometry(QtCore.QRect(42, 192, 75, 34))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=calculator)
        self.pushButton_4.setGeometry(QtCore.QRect(123, 192, 75, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(parent=calculator)
        self.label_3.setGeometry(QtCore.QRect(40, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"color:red\n"
"}")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "SimpleCalculator"))
        self.label.setText(_translate("calculator", "Number 1"))
        self.label_2.setText(_translate("calculator", "Number 2"))
        self.input1.setPlaceholderText(_translate("calculator", "Enter First Number"))
        self.input2.setPlaceholderText(_translate("calculator", "Enter Second Number"))
        self.pluse.setText(_translate("calculator", "+"))
        self.pluse.clicked.connect(self.add)
        self.pushButton_2.setText(_translate("calculator", "-"))
        self.pushButton_2.clicked.connect(self.sub)
        self.pushButton_3.setText(_translate("calculator", "x"))
        self.pushButton_3.clicked.connect(self.multi)
        self.pushButton_4.setText(_translate("calculator", "/"))
        self.pushButton_4.clicked.connect(self.div)
        self.label_3.setText(_translate("calculator", ""))

    def add(self):
        num1 = int(self.input1.text())
        num2 = int(self.input2.text())
        number = num1 + num2
        self.label_3.setText(f"Sum is : {str(number)}")

    def multi(self):
        num1 = int(self.input1.text())
        num2 = int(self.input2.text())
        number = num1 * num2
        self.label_3.setText(f"Multiply is : {str(number)}")

    def sub(self):
        num1 = int(self.input1.text())
        num2 = int(self.input2.text())
        number = num1 - num2
        self.label_3.setText(f"Sub is : {str(number)}")

    def div(self):
        num1 = int(self.input1.text())
        num2 = int(self.input2.text())
        number = num1 / num2
        self.label_3.setText(f"Division is : {str(number)}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calculator = QtWidgets.QWidget()
    ui = Ui_calculator()
    ui.setupUi(calculator)
    calculator.show()
    sys.exit(app.exec())
